quarkus.endive.modules.qrcode.name=io.quarkiverse.endive.it.QRCodeModule
quarkus.endive.modules.qrcode.wasm-file=src/main/resources/wasm/qr-generator.wasm

quarkus.log.category."io.quarkiverse.endive".level=DEBUG
quarkus.log.category."io.quarkiverse.endive".min-level=DEBUG
