quarkus.endive.modules.go-cel.name=io.quarkiverse.endive.it.GoCelModule
# The Wasm module payload is configurable either as a file
quarkus.endive.modules.go-cel.wasm-file=src/main/resources/wasm/go-cel.wasm
# Or as a classpath resource, but file the file based configuration takes precedence
#quarkus.endive.modules.go-cel.wasm-resource=go-cel.wasm
