quarkus.endive.modules.operation-static.name=io.quarkiverse.endive.it.StaticOperationModule
# The Wasm module payload is configurable either as a file
quarkus.endive.modules.operation-static.wasm-file=src/main/resources/wasm/operation.wasm
# Or as a classpath resource, but file the file based configuration takes precedence
#quarkus.endive.modules.operation-static.wasm-resource=operation.wasm

quarkus.endive.modules.operation-dynamic.name=io.quarkiverse.endive.it.DynamicOperationModule
# The Wasm module payload is not defined as it's expected to be provided dynamically at runtime

quarkus.log.category."io.quarkiverse.endive".level=DEBUG
# IMPORTANT for Native Mode: Set the floor level allowed at build-time
# Default is DEBUG, but if you need TRACE, you must set this
quarkus.log.category."io.quarkiverse.endive".min-level=DEBUG
