package io.quarkiverse.endive.runtime.wasm;

import java.util.Objects;
import java.util.function.Function;
import java.util.function.Supplier;

import io.quarkus.logging.Log;
import run.endive.compiler.MachineFactoryCompiler;
import run.endive.runtime.Instance;
import run.endive.runtime.InterpreterMachine;
import run.endive.runtime.Machine;

/**
 * Expects that build-time generated bytecode cannot be used.
 */
public class DevTestModeMachineFactoryProvider implements Supplier<Function<Instance, Machine>> {
    private final ExecutionMode executionMode;

    public DevTestModeMachineFactoryProvider(final ExecutionMode executionMode) {
        this.executionMode = executionMode;
    }

    @Override
    public Function<Instance, Machine> get() {
        // DEV/TEST mode live reload works, use the configured execution mode for both static and dynamic Wasm
        // modules
        if (Objects.requireNonNull(executionMode) == ExecutionMode.RuntimeCompiler) {
            Log.info("  DEV/TEST mode, runtime compiler will be used");
            return MachineFactoryCompiler::compile;
        } else {
            Log.info("  DEV/TEST mode, interpreter will be used");
            return InterpreterMachine::new;
        }
    }
}
