package io.quarkiverse.endive.deployment.items;

import java.nio.file.Path;
import java.util.List;

import io.quarkus.builder.item.MultiBuildItem;

/**
 * Store data produced by the code generation process for a given Wasm module.
 * <p>
 * An instance of {@link GeneratedWasmCodeBuildItem} contains a reference to the name of a configured Wasm
 * module, a collection of classes that represent the generated bytecode, a reference to the generated meta Wasm and
 * a collection of raw sources that represent the generated Java classes.
 * </p>
 */
public final class GeneratedWasmCodeBuildItem extends MultiBuildItem {
    private final String name;
    private final List<Path> classes;
    private final Path metaWasm;
    private final Path javaSources;

    public GeneratedWasmCodeBuildItem(final String name, final List<Path> classes, final Path metaWasm,
            final Path javaSources) {
        this.name = name;
        this.classes = classes;
        this.metaWasm = metaWasm;
        this.javaSources = javaSources;
    }

    public String getName() {
        return name;
    }

    public List<Path> getClasses() {
        return classes;
    }

    public Path getMetaWasm() {
        return metaWasm;
    }

    public Path getJavaSources() {
        return javaSources;
    }

    @Override
    public String toString() {
        return "GeneratedWasmCodeBuildItem{" +
                "name='" + name + '\'' +
                ", metaWasm=" + metaWasm +
                ", javaSources=" + javaSources +
                '}';
    }
}
